### ISSUE TITLE
Fix Music Genres blank icon

### ISSUE THREAD

**Issue by xmha97** [kcook98765/skin.aura#11]
Please fix Music Genres blank icon.
This problem occurred after updating to version 2.0.10.
![image](https://user-images.githubusercontent.com/23485114/150331087-fbcf137c-acdf-4160-a379-0f4788cd8837.png)

**Comment by kcook98765** [comment]
Music Genre icons were never setup in the original skin. My attempt to fix Genres in other areas accidentally displayed a fallback genre image for music. I have corrected the Genre icon logic, and now it correctly only applies to Movie/Tv Shows.

As for Music, I'm not sure I want to work out how to insert genre icons, as it would be quite a bit of work.
