### ISSUE TITLE
Last update broke covers on tvshows

### ISSUE THREAD

**Issue by Rootzpower** [kcook98765/skin.aura#12]
Hi

Last update broke covers in tvshows.
Not display covers on mode "Big covers"; "Info List" and "List"

I've similar problem 2021 and you fix it. Here's the thread:
https://forum.kodi.tv/showthread.php?tid=328558&pid=3025286#pid3025286

I do some job, and the last good know version for me is 2.0.8.
2.0.9 to last one don't display covers correctly.

I upload video to prove it.

Can you fix it please?
Thanks

https://user-images.githubusercontent.com/15384112/152367590-e24e9381-0d54-48cf-aadf-1784636e6863.mp4

**Comment by kcook98765** [comment]
Sorry about that. Try the latest V2.0.16

**Comment by Rootzpower** [comment]
Thanks for the fix :)
