### ISSUE TITLE
Fanart/Poster can not be changed

### ISSUE THREAD

**Issue by traab-github** [kcook98765/skin.aura#13]
When i try to change the Posters, nothing happens when i push the Poster/Fanart Button.

**Comment by kcook98765** [comment]
I need a bit more information to go on. Where is the "button" you are pushing, and from where?
Maybe a screen shot would help me understand.

**Comment by traab-github** [comment]
Oh yes, sorry, i attached a Screenshot of the Button. It's when you are in the Information of the Movies (or Series).

![index](https://user-images.githubusercontent.com/81415413/152676781-52b9e138-86bd-43ec-b523-d33eed101236.jpg)

**Comment by kcook98765** [comment]
You must be running another Aura skin, as this version had that option removed when I setup this version. I will have to look into how to make it work for this repository of the Aura skin. But again, you must have another version from another repository?

**Comment by traab-github** [comment]
Ah yes, i got this from a other repository. I now reinstalled the latest Version from you and there are no options to change the Poster/Fanart - and also the Refresh Button is removed. :-( 

Is there a reason for that? I love to change the Poster and also need for some time the Refresh Button.

**Comment by kcook98765** [comment]
I had removed it as I was trying to clean up code for Matrix. I have added back in those 2 options, with V2.0.20

Please do test it out, I think it is working now.

**Comment by kcook98765** [comment]
correction, one of the options you wanted relies on script.artwork.beef, so if you have that, try V2.0.21 (which enables these options with that addon).

If you have a different addon for art, let me know and I could see about setting it up.

**Comment by traab-github** [comment]
Wow great, thank - this works now with the Poster and Fanart. You are my hero!

I have one more question, when playing a movie/file, there is the possibilty to change the subtiltes with one click, but not the language of the audio track.

In the Arctic Horizon Skin, there is a possibilty to change both - and the language is shown as a acronym (f.e. CHI and ENG) over the button for audio and subtiltes. 

THAT would be really awesome to add to the Aura Skin as well. 

I attached a Picture for better understanding.

![WhatsApp Image 2022-02-09 at 18 09 03](https://user-images.githubusercontent.com/81415413/153253776-c4930710-e0dd-48e0-be9b-01c1d9b3dd7d.jpeg)

**Comment by kcook98765** [comment]
Try V2.0.22 , I don't have any alt language to test changing, but the display of language (and new audio selector) is in the OSD now.

**Comment by traab-github** [comment]
Awesome, thank you very much. Really great that you response so fast and also make customers wishes happen. Thanks!
