### ISSUE TITLE
remove WonderfulSubs from search

### ISSUE THREAD

**Issue by daveftw84** [kcook98765/skin.aura#18]
ActivateWindow(1136) 
it uses tmdb helper and other addons like youtube to search, anyway to remove the dead addon? WonderfulSubs

**Comment by kcook98765** [comment]
I can not locate anything related to WonderfulSubs in this skin. Maybe this is coming from another skin or a separate Addon install?

**Comment by daveftw84** [comment]
skin.auramod\shortcuts\searchmenus.DATA.xml
  <shortcut>
    <label>WonderfulSubs</label>
    <label2>$LOCALIZE[571]</label2>
    <icon>DefaultShortcut.png</icon>
    <action>DefaultSearch-WonderfulSubs</action>
  </shortcut>

**Comment by kcook98765** [comment]
this skin is not "skin.auramod" , I think you have a different skin than this one?

**Comment by kcook98765** [comment]
The references you noted, I see in the skin at:

https://github.com/skyfsza/skin.auramod

So I am closing this one.

**Comment by kcook98765** [comment]
closing.
