### ISSUE TITLE
Mouse does not work properly in submenus

### ISSUE THREAD

**Issue by gtkingbuild** [kcook98765/skin.aura#2]
Hello, I have a problem in kodi 19 with the pc mouse and the Aura skin, and it is that I cannot select any item from the category submenus, I do not know if this same problem will happen to someone else or if it has a solution. Greetings and thank you.

https://user-images.githubusercontent.com/68242121/141450737-78728693-ae59-4133-b622-20ed3a759dbc.mp4

**Comment by kyoforkshomebrews** [comment]
For me it works. Did you enable mouse compatibility in `Settings > Skin > Main Menu` ?

**Comment by gtkingbuild** [comment]
> For me it works. Did you enable mouse compatibility in `Settings > Skin > Main Menu` ?

Yes, of course, in fact if that option is not enabled the mouse pointer does not appear nor can it be moved

**Comment by kcook98765** [comment]
Hm, seems to have been a problem in the original Auar skin as well:

https://github.com/jurialmunkey/skin.aura/issues/72

No updates about the issue though.

When I get some time, I will try to see what I can do (though skinning is still very new to me).

I don't use mouse, but tested on Windows and do see there is an issue.

**Comment by kcook98765** [comment]
Actually, I had to enable a second setting and now it does work.

See original Aura post:

https://forum.kodi.tv/showthread.php?tid=328558

And note, you need to enable "Skin Settings" > "Home" > "Mouse Compatibility"

After I did that, the mouse worked with the submenus.
