### ISSUE TITLE
Where is genre icons?

### ISSUE THREAD

**Issue by xmha97** [kcook98765/skin.aura#9]
Hi @kcook98765 
Where is genre icons?
![image](https://user-images.githubusercontent.com/23485114/149579711-8047cb31-3509-4527-840d-95b7fd0caeae.png)

**Comment by kcook98765** [comment]
The main thread for the original Aura skin can help:

https://forum.kodi.tv/showthread.php?tid=328558

Per first post under Dependencies:

"resource.images.moviegenreicons.transparent"

but also supports :
The horizon genre icon pack is supported, so I also recommend installing it:
https://github.com/Swageroni/resource.images.moviegenreicons.horizon

So the 2 supported genre icons are:

resource.images.moviegenreicons.horizon
resource.images.moviegenreicons.transparent

If you have another resource you want to use, I believe I could set that up if you can point me to the repository for it, though it is a "first found" type logic:

IE, first one found would display:

1) resource.images.moviegenreicons.horizon
2) resource.images.moviegenreicons.transparent

So I could add a new one to top of this list, and, if found to be installed, would use it.

These are setup in Includes_Images.xml under the "Image_GenreIcons_Path" variable name area of this file.

**Comment by xmha97** [comment]
Thanks for your explanation.
There is no photo for the "Drama" genre, not all of the repositories you mentioned have not been updated since 2017. Do I have to create a new repository?

Please also explain about music genres.
![image](https://user-images.githubusercontent.com/23485114/149604615-94d258c5-be46-42e2-91cb-e6b4d1589ce3.png)
